In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(
    filepath_or_buffer='data/imdb.csv'
)

# EDA

In [3]:
df.head(10)

,Movie_Title,YR_Released,Rating,Num_Reviews,Movie_ID,Record,Runtime
0,Code Name: K.O.Z.,2015,1.4,24623,tt4458206,Bottom 250 Movies,114.0
1,Saving Christmas,2014,1.5,12765,tt4009460,Bottom 250 Movies,80.0
2,Superbabies: Baby Geniuses 2,2004,1.6,26505,tt0270846,Bottom 250 Movies,88.0
3,Daniel the Wizard,2004,1.6,13295,tt0421051,Bottom 250 Movies,81.0
4,Manos: The Hands of Fate,1966,1.7,31808,tt0060666,Bottom 250 Movies,70.0
5,Pledge This!,2006,1.7,15836,tt0417056,Bottom 250 Movies,91.0
6,Dünyayi Kurtaran Adam'in Oglu,2006,1.8,14110,tt0808240,Bottom 250 Movies,110.0
7,Foodfight!,2012,1.8,5740,tt0249516,Bottom 250 Movies,91.0
8,Birdemic: Shock and Terror,2010,1.8,15919,tt1316037,Bottom 250 Movies,105.0
9,Álom.net,2009,1.9,8502,tt1309000,Bottom 250 Movies,NaN

In [4]:
df.tail()

,Movie_Title,YR_Released,Rating,Num_Reviews,Movie_ID,Record,Runtime
845,Pirates of the Caribbean: The Curse of the Bla...,2003,8.0,872441,tt0325980,Top 250 Movies,143.0
846,What Ever Happened to Baby Jane?,1962,8.0,37906,tt0056687,Top 250 Movies,134.0
847,"Paris, Texas",1984,8.0,55587,tt0087884,Top 250 Movies,145.0
848,Drishyam,2015,8.0,40777,tt4430212,Top 250 Movies,163.0
849,PK,2014,8.0,106375,tt2338151,Top 250 Movies,153.0

In [5]:
df.shape

(850, 7)

In [6]:
df.columns

Index(['Movie_Title', 'YR_Released', 'Rating', 'Num_Reviews', 'Movie_ID',
       'Record', 'Runtime'],
      dtype='object')

In [7]:
df.values

array([['Code Name: K.O.Z.', 2015, 1.4, ..., 'tt4458206',
        'Bottom 250 Movies', 114.0],
       ['Saving Christmas', 2014, 1.5, ..., 'tt4009460',
        'Bottom 250 Movies', 80.0],
       ['Superbabies: Baby Geniuses 2', 2004, 1.6, ..., 'tt0270846',
        'Bottom 250 Movies', 88.0],
       ...,
       ['Paris, Texas', 1984, 8.0, ..., 'tt0087884', 'Top 250 Movies',
        145.0],
       ['Drishyam', 2015, 8.0, ..., 'tt4430212', 'Top 250 Movies', 163.0],
       ['PK', 2014, 8.0, ..., 'tt2338151', 'Top 250 Movies', 153.0]],
      shape=(850, 7), dtype=object)

In [8]:
df.describe()

       YR_Released      Rating   Num_Reviews     Runtime
count   850.000000  850.000000  8.500000e+02  849.000000
mean   1991.375294    7.371882  2.595814e+05  130.771496
std      22.855960    1.886546  3.467833e+05   33.232523
min    1921.000000    1.400000  1.920000e+03   54.000000
25%    1977.250000    7.500000  1.276900e+04  105.000000
50%    1999.000000    8.100000  7.861750e+04  129.000000
75%    2009.000000    8.200000  4.437150e+05  153.000000
max    2017.000000    9.200000  1.829037e+06  320.000000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 850 entries, 0 to 849
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Movie_Title  850 non-null    object
 1   YR_Released  850 non-null    int64
 2   Rating       850 non-null    float64
 3   Num_Reviews  850 non-null    int64
 4   Movie_ID     850 non-null    object
 5   Record       850 non-null    object
 6   Runtime      849 non-null    float64
dtypes: float64(2), int64(2), object(3)
memory usage: 46.6+ KB

In [10]:
df.isnull().sum()

Movie_Title    0
YR_Released    0
Rating         0
Num_Reviews    0
Movie_ID       0
Record         0
Runtime        1
dtype: int64

# .loc vs .iloc

In [11]:
df.loc[1, 'Movie_Title']

'Saving Christmas'

In [12]:
df.iloc[1, 0]

'Saving Christmas'

In [13]:
df.loc[1, 'Num_Reviews']

np.int64(12765)

In [14]:

#* Saving Christmas filminin Num of Reviews bilgisini yazdırın
df.iloc[1, 3]

np.int64(12765)

In [15]:

#* 5 ile 10 satırlardı ki filmlerin isimlerini ekrana yazdırın
df.loc[5:10, 'Movie_Title']

5                       Pledge This!
6      Dünyayi Kurtaran Adam'in Oglu
7                         Foodfight!
8         Birdemic: Shock and Terror
9                           Álom.net
10    Titanic - La leggenda continua
Name: Movie_Title, dtype: object

In [16]:

#* ilk 10 filmi ekrana yazdırın
df.loc[:10, 'Movie_Title']

0                  Code Name: K.O.Z.
1                   Saving Christmas
2       Superbabies: Baby Geniuses 2
3                  Daniel the Wizard
4           Manos: The Hands of Fate
5                       Pledge This!
6      Dünyayi Kurtaran Adam'in Oglu
7                         Foodfight!
8         Birdemic: Shock and Terror
9                           Álom.net
10    Titanic - La leggenda continua
Name: Movie_Title, dtype: object

In [17]:

#* 10 ile 20 satırların Movie_Title, Num_Reviews
df.loc[10:20, ['Movie_Title', 'Num_Reviews']]

                        Movie_Title  Num_Reviews
10   Titanic - La leggenda continua         8421
11                   Disaster Movie        77553
12                    Zombie Nation         7730
13          The Hottie & the Nottie        34098
14       Keloglan Karaprens'e Karsi         8502
15             From Justin to Kelly        23920
16                     A Fox's Tale         7953
17  Ram Gopal Varma's Indian Flames         6028
18                  Going Overboard        10938
19         Emret Komutanim: Sah Mat         6354
20     Attack of the Jurassic Shark         2983

In [18]:
# loc ile çözülecek
# 'Movie_Title', 'Rating', 'Num_Reviews'
df.loc[:, ['Movie_Title', 'Rating', 'Num_Reviews']]

                                           Movie_Title  Rating  Num_Reviews
0                                    Code Name: K.O.Z.     1.4        24623
1                                     Saving Christmas     1.5        12765
2                         Superbabies: Baby Geniuses 2     1.6        26505
3                                    Daniel the Wizard     1.6        13295
4                             Manos: The Hands of Fate     1.7        31808
..                                                 ...     ...          ...
845  Pirates of the Caribbean: The Curse of the Bla...     8.0       872441
846                   What Ever Happened to Baby Jane?     8.0        37906
847                                       Paris, Texas     8.0        55587
848                                           Drishyam     8.0        40777
849                                                 PK     8.0       106375

[850 rows x 3 columns]

In [19]:
# 1. ve 7. satırların Movie_Title ve Rating bilgileri getirilsin
# iloc ile yapılacak
df.iloc[
    [1, 7], [0, 2]
]

        Movie_Title  Rating
1  Saving Christmas     1.5
7        Foodfight!     1.8

In [20]:
df['Movie_Title']

0                                      Code Name: K.O.Z.
1                                       Saving Christmas
2                           Superbabies: Baby Geniuses 2
3                                      Daniel the Wizard
4                               Manos: The Hands of Fate
                             ...
845    Pirates of the Caribbean: The Curse of the Bla...
846                     What Ever Happened to Baby Jane?
847                                         Paris, Texas
848                                             Drishyam
849                                                   PK
Name: Movie_Title, Length: 850, dtype: object

In [21]:
df['Movie_Title'][20:50]

20    Attack of the Jurassic Shark
21                    Potato Salad
22                    Ben & Arthur
23         La leggenda del Titanic
24                      Himmatwala
25    Birdemic 2: The Resurrection
26                 Monster a-Go Go
27               House of the Dead
28               Who's Your Caddy?
29                      Humshakals
30                      Hobgoblins
31                         Glitter
32        The Beast of Yucca Flats
33                 Son of the Mask
34                       Crossover
35                    Space Mutiny
36       Night Train to Mundo Fine
37      Extra Terrestrial Visitors
38                    Dracula 3000
39      The Wild World of Batwoman
40                     Surf School
41                      Epic Movie
42               Alone in the Dark
43                The Starfighters
44                  Leonard Part 6
45                   Final Justice
46                           Eegah
47                Die Hard Dracula
48                       The Class
49                 United Passions
Name: Movie_Title, dtype: object

In [22]:
df[['Movie_Title', 'Num_Reviews']][10:20]

                        Movie_Title  Num_Reviews
10   Titanic - La leggenda continua         8421
11                   Disaster Movie        77553
12                    Zombie Nation         7730
13          The Hottie & the Nottie        34098
14       Keloglan Karaprens'e Karsi         8502
15             From Justin to Kelly        23920
16                     A Fox's Tale         7953
17  Ram Gopal Varma's Indian Flames         6028
18                  Going Overboard        10938
19         Emret Komutanim: Sah Mat         6354

In [23]:
df.columns

Index(['Movie_Title', 'YR_Released', 'Rating', 'Num_Reviews', 'Movie_ID',
       'Record', 'Runtime'],
      dtype='object')

In [24]:
# 'Movie_Title', 'Rating', 'Num_Reviews' sütunlarını listeleyin
df[['Movie_Title', 'Rating', 'Num_Reviews']]

                                           Movie_Title  Rating  Num_Reviews
0                                    Code Name: K.O.Z.     1.4        24623
1                                     Saving Christmas     1.5        12765
2                         Superbabies: Baby Geniuses 2     1.6        26505
3                                    Daniel the Wizard     1.6        13295
4                             Manos: The Hands of Fate     1.7        31808
..                                                 ...     ...          ...
845  Pirates of the Caribbean: The Curse of the Bla...     8.0       872441
846                   What Ever Happened to Baby Jane?     8.0        37906
847                                       Paris, Texas     8.0        55587
848                                           Drishyam     8.0        40777
849                                                 PK     8.0       106375

[850 rows x 3 columns]

In [25]:
# 'Movie_Title', 'Rating' ilk beşsm atırını ekrana basın
# Path I
df[['Movie_Title', 'Rating']].head()
# Path II
df[['Movie_Title', 'Rating']][:5]

                    Movie_Title  Rating
0             Code Name: K.O.Z.     1.4
1              Saving Christmas     1.5
2  Superbabies: Baby Geniuses 2     1.6
3             Daniel the Wizard     1.6
4      Manos: The Hands of Fate     1.7

# Data Fitering

In [26]:
# 2000'den sonra yayınlanmış rating en çok olan top 10 movie
(
    df.query('YR_Released > 2000')
        [['Movie_Title', 'YR_Released','Rating']]
        .sort_values(by='Rating', ascending=False)
        .head(10)
)

                                           Movie_Title  YR_Released  Rating
103                                    The Dark Knight         2008     9.0
603                                    The Dark Knight         2008     9.0
607      The Lord of the Rings: The Return of the King         2003     8.9
106      The Lord of the Rings: The Return of the King         2003     8.9
109  The Lord of the Rings: The Fellowship of the Ring         2001     8.8
610  The Lord of the Rings: The Fellowship of the Ring         2001     8.8
112                                          Inception         2010     8.7
113              The Lord of the Rings: The Two Towers         2002     8.7
613                                          Inception         2010     8.7
614              The Lord of the Rings: The Two Towers         2002     8.7

In [27]:
# (
#     df[df['YR_Released'] > 2000]
#         .loc[:, ['Movie_Title', 'YR_Released','Rating']]
#         .sort_values(by='Rating', ascending=False)
#         .head(10)
# )

(
    df[df['YR_Released'] > 2000]
        [['Movie_Title', 'YR_Released','Rating']]
        .sort_values(by='Rating', ascending=False)
        .head(10)
)

                                           Movie_Title  YR_Released  Rating
103                                    The Dark Knight         2008     9.0
603                                    The Dark Knight         2008     9.0
607      The Lord of the Rings: The Return of the King         2003     8.9
106      The Lord of the Rings: The Return of the King         2003     8.9
109  The Lord of the Rings: The Fellowship of the Ring         2001     8.8
610  The Lord of the Rings: The Fellowship of the Ring         2001     8.8
112                                          Inception         2010     8.7
113              The Lord of the Rings: The Two Towers         2002     8.7
613                                          Inception         2010     8.7
614              The Lord of the Rings: The Two Towers         2002     8.7

In [28]:
# Rating'i 7.0 ve 9.0 arasında olan filmlerin 'Movie_Title','Rating', 'Num_Reviews' sütunları Rating sütununa göre çoktan aza sıralayarak getirin

(
    df[
        (df['Rating'] > 7.0) & (df['Rating'] < 9.0)
    ][['Movie_Title', 'YR_Released', 'Rating']]
    .sort_values(by='Rating', ascending=False)   
)

                                       Movie_Title  YR_Released  Rating
607  The Lord of the Rings: The Return of the King         2003     8.9
606                                   Pulp Fiction         1994     8.9
604                                   12 Angry Men         1957     8.9
605                               Schindler's List         1993     8.9
106  The Lord of the Rings: The Return of the King         2003     8.9
..                                             ...          ...     ...
563                                 Gabbar is Back         2015     7.1
564                                      Raajneeti         2010     7.1
565                                          Wazir         2016     7.1
566                               Yennai Arindhaal         2015     7.1
567                                   Dasavatharam         2008     7.1

[728 rows x 3 columns]

In [29]:
df.columns

Index(['Movie_Title', 'YR_Released', 'Rating', 'Num_Reviews', 'Movie_ID',
       'Record', 'Runtime'],
      dtype='object')

In [30]:
# Num_Reviews 2000'den 3000'den az olan filmlerin 'Movie_Title', 'Rating', 'Num_Reviews'
# Num_Reviews verisi çoktan aza sort edelim
(
    df.query('2000 < Num_Reviews < 3000')
        .loc[: , ['Movie_Title', 'Rating', 'Num_Reviews']]
        .sort_values(
            by='Num_Reviews', 
            ascending=False
        )
)

                                 Movie_Title  Rating  Num_Reviews
20              Attack of the Jurassic Shark     2.0         2983
48                                 The Class     2.4         2968
23                   La leggenda del Titanic     2.0         2883
79           Dis - en historie om kjærlighet     2.7         2875
78  Boggy Creek II: And the Legend Continues     2.7         2838
45                             Final Justice     2.4         2792
91                              Time Chasers     2.7         2756
92                                Devil Fish     2.7         2624
77                          Zombie Nightmare     2.7         2593
66                      The Maize: The Movie     2.5         2540
71                           Prince of Space     2.6         2531
95                       I Accuse My Parents     2.7         2444
67                        The Touch of Satan     2.6         2442
97                     Stjerner uden hjerner     2.8         2332
58               Invasion of the Neptune Men     2.5         2246
99                 Warrior of the Lost World     2.8         2151
98                        Ghosts Can't Do It     2.8         2074

In [31]:
# Movie_Title içerisinde "King" ifadesi geçen ve Rating 7.0'den büyük olan filmlerin 'Movie_Title', 'Rating', 'Num_Reviews'
# Rating sütununa göre çoktan aza sıralayalım
(
    df.query('Movie_Title.str.contains("King") & Rating >= 7.0')
        .loc[:, ['Movie_Title', 'Rating', 'Num_Reviews']]
        .sort_values(
            by='Rating', 
            ascending=False
        )
)

                                       Movie_Title  Rating  Num_Reviews
106  The Lord of the Rings: The Return of the King     8.9      1311271
607  The Lord of the Rings: The Return of the King     8.9      1311271
139                                  The Lion King     8.5       708441
648                                  The Lion King     8.5       708441
329                              The King's Speech     8.0       538099

In [32]:
df[
    (df["Movie_Title"].str.contains("King")) & (df['Rating'] > 7.0)
].loc[:, ['Movie_Title', 'Rating', 'Num_Reviews']].sort_values(by='Rating', ascending=False)

                                       Movie_Title  Rating  Num_Reviews
106  The Lord of the Rings: The Return of the King     8.9      1311271
607  The Lord of the Rings: The Return of the King     8.9      1311271
139                                  The Lion King     8.5       708441
648                                  The Lion King     8.5       708441
329                              The King's Speech     8.0       538099

# Group By

In [43]:
# Filmlerin yayınlanma yıllarına göre toplam Num_Reviews sayılarını yazdıralım
# Sorunun mantığı: YR_Released sütununa göre veriyi gruplayalım, Num_Reviews sütununu toplayalım
# Path I
df.groupby(by='YR_Released')['Num_Reviews'].sum().sort_values(ascending=False)

YR_Released
1994    12360599
1999    10961782
1995    10012874
2003     8759224
2010     8043754
          ...
1945       55125
1930       49233
1928       29550
1935       26078
1947       25158
Name: Num_Reviews, Length: 88, dtype: int64

In [ ]:
# Path II
(
    df.groupby(by='YR_Released')
        .agg({
            'Num_Reviews': 'sum'
        })
        .query('7000000 < Num_Reviews < 10000000')
        .sort_values(
            by='Num_Reviews', 
            ascending=False
        )
)

             Num_Reviews
YR_Released
1994            12360599
1999            10961782
1995            10012874
2003             8759224
2010             8043754
...                  ...
1945               55125
1930               49233
1928               29550
1935               26078
1947               25158

[88 rows x 1 columns]

In [47]:
# YR_Released göre veriyi gruplayalım
# Rating Ortalmaası bulalım
(
    df.groupby(by='YR_Released')
        .agg({
            'Rating': 'mean'
        })
        .query('8.0 < Rating < 10.0')
        .sort_values(
            by='Rating', 
            ascending=False
        )
)

               Rating
YR_Released
1972         8.800000
1936         8.500000
1942         8.500000
1931         8.466667
1981         8.433333
1957         8.350000
1979         8.337500
1954         8.328571
1977         8.325000
1991         8.312500
1921         8.300000
1950         8.266667
1941         8.225000
1946         8.216667
1986         8.200000
1925         8.200000
1948         8.200000
1952         8.200000
1949         8.166667
1940         8.162500
1973         8.150000
1926         8.150000
1927         8.150000
1993         8.127273
1939         8.116667
1928         8.100000
1955         8.100000
1934         8.100000
1982         8.100000
1969         8.066667
1967         8.066667
1945         8.050000
1953         8.050000
1956         8.050000

In [49]:
df.sort_values(by='Rating', ascending=False)

,Movie_Title,YR_Released,Rating,Num_Reviews,Movie_ID,Record,Runtime
601,The Godfather,1972,9.2,1249333,tt0068646,Top 250 Movies,175.0
101,The Godfather,1972,9.2,1249333,tt0068646,Top 250 Eng Movies,175.0
100,The Shawshank Redemption,1994,9.2,1829037,tt0111161,Top 250 Eng Movies,142.0
600,The Shawshank Redemption,1994,9.2,1829037,tt0111161,Top 250 Movies,142.0
603,The Dark Knight,2008,9.0,1808543,tt0468569,Top 250 Movies,152.0
...,...,...,...,...,...,...,...
4,Manos: The Hands of Fate,1966,1.7,31808,tt0060666,Bottom 250 Movies,70.0
3,Daniel the Wizard,2004,1.6,13295,tt0421051,Bottom 250 Movies,81.0
2,Superbabies: Baby Geniuses 2,2004,1.6,26505,tt0270846,Bottom 250 Movies,88.0
1,Saving Christmas,2014,1.5,12765,tt4009460,Bottom 250 Movies,80.0
0,Code Name: K.O.Z.,2015,1.4,24623,tt4458206,Bottom 250 Movies,114.0