In [2]:
import pandas as pd

In [3]:
customers = {
    'customer_id': [1, 2, 3],
    'full_name': ['Burak Yılmaz', 'Hakan Yılmaz', 'İpek Yılmaz'],
    'address': ['Ataköy', 'Sarıyer', 'Sarıyer']
}

orders = {
    'order_id': [1001, 1002, 1003, 1004, 1005],
    'customer_id': [1, 2, 3, 4, 5],
    'order_revenue': [2456, 1234, 4567, 2345, 9876]
}

df_customers = pd.DataFrame(customers)
df_orders = pd.DataFrame(orders)

In [4]:
df_customers

   customer_id     full_name  address
0            1  Burak Yılmaz   Ataköy
1            2  Hakan Yılmaz  Sarıyer
2            3   İpek Yılmaz  Sarıyer

In [5]:
df_orders

   order_id  customer_id  order_revenue
0      1001            1           2456
1      1002            2           1234
2      1003            3           4567
3      1004            4           2345
4      1005            5           9876

# Merge

In [6]:
# inner merge
inner_merge = pd.merge(
    left=df_customers,
    right=df_orders,
    on='customer_id',
    #left_on='column_name',
    #right_on='column_name'
    how='inner'
)

inner_merge

   customer_id     full_name  address  order_id  order_revenue
0            1  Burak Yılmaz   Ataköy      1001           2456
1            2  Hakan Yılmaz  Sarıyer      1002           1234
2            3   İpek Yılmaz  Sarıyer      1003           4567

In [9]:
# left merge
left_merge = pd.merge(
    left=df_orders,
    right=df_customers,
    on='customer_id',
    how='left'
)

left_merge

   order_id  customer_id  order_revenue     full_name  address
0      1001            1           2456  Burak Yılmaz   Ataköy
1      1002            2           1234  Hakan Yılmaz  Sarıyer
2      1003            3           4567   İpek Yılmaz  Sarıyer
3      1004            4           2345           NaN      NaN
4      1005            5           9876           NaN      NaN

In [10]:
# right merge
right_merge = pd.merge(
    left=df_customers,
    right=df_orders,
    on='customer_id',
    how='right'
)

right_merge

   customer_id     full_name  address  order_id  order_revenue
0            1  Burak Yılmaz   Ataköy      1001           2456
1            2  Hakan Yılmaz  Sarıyer      1002           1234
2            3   İpek Yılmaz  Sarıyer      1003           4567
3            4           NaN      NaN      1004           2345
4            5           NaN      NaN      1005           9876