In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(
    filepath_or_buffer='data/auto.csv'
)

In [4]:
df

,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
200,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
201,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
202,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
203,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [5]:
df.shape

(204, 26)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 26 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   3            204 non-null    int64
 1   ?            204 non-null    object
 2   alfa-romero  204 non-null    object
 3   gas          204 non-null    object
 4   std          204 non-null    object
 5   two          204 non-null    object
 6   convertible  204 non-null    object
 7   rwd          204 non-null    object
 8   front        204 non-null    object
 9   88.6         204 non-null    float64
 10  168.8        204 non-null    float64
 11  64.1         204 non-null    float64
 12  48.8         204 non-null    float64
 13  2548         204 non-null    int64
 14  dohc         204 non-null    object
 15  four         204 non-null    object
 16  130          204 non-null    int64
 17  mpfi         204 non-null    object
 18  3.47         204 non-null    object
 19  2.68         204 non-null    object
 20  9.0          204 non-null    float64
 21  111          204 non-null    object
 22  5000         204 non-null    object
 23  21           204 non-null    int64
 24  27           204 non-null    int64
 25  13495        204 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.6+ KB

In [7]:
df.columns =  ["symboling", "normalized-losses", "make", "fuel-type", "aspiration", "num-of-doors", "body-style",
              "drive-wheels", "engine-location", "wheel-base", "length", "width", "height", "curb-weight",
              "engine-type", "num-of-cylinders", "engine-size", "fuel-system", "bore", "stroke", "compression-ratio",
              "horsepower", "peak-rpm", "city-mpg", "highway-mpg", "price"]

df.columns

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg', 'price'],
      dtype='object')

In [8]:
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
200,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
201,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
202,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
203,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [9]:
df.replace(
    to_replace='?',
    value=np.nan,
    inplace=True
)

df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250

In [10]:
df.isnull().sum()

symboling             0
normalized-losses    40
make                  0
fuel-type             0
aspiration            0
num-of-doors          2
body-style            0
drive-wheels          0
engine-location       0
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  4
stroke                4
compression-ratio     0
horsepower            2
peak-rpm              2
city-mpg              0
highway-mpg           0
price                 4
dtype: int64

In [11]:
missing_values_df = df.isnull()

missing_values_df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [12]:
missing_dict = {}

for column_name in missing_values_df.columns.tolist():
    print(
        '============================\n'
        f'Column Name: {column_name}\n'
        f'Missing Values Count: {missing_values_df[column_name].value_counts()}'
    )

============================
Column Name: symboling
Missing Values Count: symboling
False    204
Name: count, dtype: int64
============================
Column Name: normalized-losses
Missing Values Count: normalized-losses
False    164
True      40
Name: count, dtype: int64
============================
Column Name: make
Missing Values Count: make
False    204
Name: count, dtype: int64
============================
Column Name: fuel-type
Missing Values Count: fuel-type
False    204
Name: count, dtype: int64
============================
Column Name: aspiration
Missing Values Count: aspiration
False    204
Name: count, dtype: int64
============================
Column Name: num-of-doors
Missing Values Count: num-of-doors
False    202
True       2
Name: count, dtype: int64
============================
Column Name: body-style
Missing Values Count: body-style
False    204
Name: count, dtype: int64
============================
Column Name: drive-wheels
Missing Values Count: drive-wheels
False    204
Name: count, dtype: int64
============================
Column Name: engine-location
Missing Values Count: engine-location
False    204
Name: count, dtype: int64
============================
Column Name: wheel-base
Missing Values Count: wheel-base
False    204
Name: count, dtype: int64
============================
Column Name: length
Missing Values Count: length
False    204
Name: count, dtype: int64
============================
Column Name: width
Missing Values Count: width
False    204
Name: count, dtype: int64
============================
Column Name: height
Missing Values Count: height
False    204
Name: count, dtype: int64
============================
Column Name: curb-weight
Missing Values Count: curb-weight
False    204
Name: count, dtype: int64
============================
Column Name: engine-type
Missing Values Count: engine-type
False    204
Name: count, dtype: int64
============================
Column Name: num-of-cylinders
Missing Values Count: num-of-cylinders
False    204
Name: count, dtype: int64
============================
Column Name: engine-size
Missing Values Count: engine-size
False    204
Name: count, dtype: int64
============================
Column Name: fuel-system
Missing Values Count: fuel-system
False    204
Name: count, dtype: int64
============================
Column Name: bore
Missing Values Count: bore
False    200
True       4
Name: count, dtype: int64
============================
Column Name: stroke
Missing Values Count: stroke
False    200
True       4
Name: count, dtype: int64
============================
Column Name: compression-ratio
Missing Values Count: compression-ratio
False    204
Name: count, dtype: int64
============================
Column Name: horsepower
Missing Values Count: horsepower
False    202
True       2
Name: count, dtype: int64
============================
Column Name: peak-rpm
Missing Values Count: peak-rpm
False    202
True       2
Name: count, dtype: int64
============================
Column Name: city-mpg
Missing Values Count: city-mpg
False    204
Name: count, dtype: int64
============================
Column Name: highway-mpg
Missing Values Count: highway-mpg
False    204
Name: count, dtype: int64
============================
Column Name: price
Missing Values Count: price
False    200
True       4
Name: count, dtype: int64

In [13]:
# ortalama değeri bulup missing value yerine yerleştirelim
df['normalized-losses'] = df['normalized-losses'].replace(
    to_replace=np.nan,
    value=df['normalized-losses'].astype(float).mean()
)

df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,1,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,2,122.0,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250

In [14]:
df['num-of-doors'].value_counts()

num-of-doors
four    114
two      88
Name: count, dtype: int64

In [15]:
df['num-of-doors'].value_counts().idxmax() # satır etiketini döner

'four'

In [16]:
df['num-of-doors'].value_counts().argmax() # index döner

np.int64(0)

In [17]:
# frekans aralığını bulup missing value yerine yerleştirelim
df['num-of-doors'] = df['num-of-doors'].replace(
    to_replace=np.nan,
    value=df['num-of-doors'].value_counts().idxmax()
)

# Veri Stadardizayonu

In [18]:
df['city_l/100km'] = 235 / df['city-mpg']
df['highway_l/100km'] = 235 / df['highway-mpg']

df[["make", 'city-mpg', 'city_l/100km']]

            make  city-mpg  city_l/100km
0    alfa-romero        21     11.190476
1    alfa-romero        19     12.368421
2           audi        24      9.791667
3           audi        18     13.055556
4           audi        19     12.368421
..           ...       ...           ...
199        volvo        23     10.217391
200        volvo        19     12.368421
201        volvo        18     13.055556
202        volvo        26      9.038462
203        volvo        19     12.368421

[204 rows x 3 columns]

# Veri Normalizasyonu & Scaling

In [19]:
df[['length', 'width', 'height']]

     length  width  height
0     168.8   64.1    48.8
1     171.2   65.5    52.4
2     176.6   66.2    54.3
3     176.6   66.4    54.3
4     177.3   66.3    53.1
..      ...    ...     ...
199   188.8   68.9    55.5
200   188.8   68.8    55.5
201   188.8   68.9    55.5
202   188.8   68.9    55.5
203   188.8   68.9    55.5

[204 rows x 3 columns]

In [20]:
df[['length', 'width', 'height']].describe()

           length       width      height
count  204.000000  204.000000  204.000000
mean   174.075000   65.916667   53.749020
std     12.362123    2.146716    2.424901
min    141.100000   60.300000   47.800000
25%    166.300000   64.075000   52.000000
50%    173.200000   65.500000   54.100000
75%    183.200000   66.900000   55.500000
max    208.100000   72.300000   59.800000

In [22]:
df['length'] = df['length'] / df['length'].max()
df['width'] = df['width'] / df['width'].max()
df['height'] = df['height'] / df['height'].max()

df[['length', 'width', 'height']]

       length     width    height
0    0.811148  0.886584  0.816054
1    0.822681  0.905947  0.876254
2    0.848630  0.915629  0.908027
3    0.848630  0.918396  0.908027
4    0.851994  0.917012  0.887960
..        ...       ...       ...
199  0.907256  0.952974  0.928094
200  0.907256  0.951591  0.928094
201  0.907256  0.952974  0.928094
202  0.907256  0.952974  0.928094
203  0.907256  0.952974  0.928094

[204 rows x 3 columns]

# Categorical Değerler İle Çalışma

In [23]:
dummy_variable_df = pd.get_dummies(df['fuel-type'], dtype='float')
dummy_variable_df

     diesel  gas
0       0.0  1.0
1       0.0  1.0
2       0.0  1.0
3       0.0  1.0
4       0.0  1.0
..      ...  ...
199     0.0  1.0
200     0.0  1.0
201     0.0  1.0
202     1.0  0.0
203     0.0  1.0

[204 rows x 2 columns]